### ISSUE TITLE
KeyError: 'J'

### ISSUE THREAD

**Issue by seyonechithrananda** [brianhie/evolocity#14]
Hi @brianhie! Thanks for the great documentation and tutorials surrounding your evolocity work.

I'm getting a keyerror when trying to generate the velocity graph from the influenza A nucleoprotein tutorial. I believe this is because the token J is an ambiguous amino acid that ESM-1B isn't trained for. What I am confused about is why this is occurring when downloading the models is still in progress. Could this be because I am using a newer version of the ESM package (fair-esm=2.0.0)?

KeyError                                  Traceback (most recent call last)
Cell In[8], line 1
----> 1 evo.tl.velocity_graph(adata)

File ~/anaconda3/lib/python3.10/site-packages/evolocity/tools/velocity_graph.py:503, in velocity_graph(adata, model_name, mkey, score, seqs, vkey, n_recurse_neighbors, random_neighbors_at_max, mode_neighbors, include_set, copy, verbose)
    501 if verbose:
    502     logg.msg('Computing likelihoods...')
--> 503 vgraph.compute_likelihoods(vocabulary, model)
    504 if verbose:
    505     print('')

File ~/anaconda3/lib/python3.10/site-packages/evolocity/tools/velocity_graph.py:322, in VelocityGraph.compute_likelihoods(self, vocabulary, model)
    319     return
    321 for seq in iterator:
--> 322     y_pred = predict_sequence_prob(
    323         seq, vocabulary, model, verbose=self.verbose
    324     )
    326     if self.score == 'lm' or self.score == 'edgerand':
    327         self.seq_probs[seq] = np.array([
    328             y_pred[i + 1, (
    329                 vocabulary[seq[i]]
   (...)
    332             )] for i in range(len(seq))
    333         ])

File ~/anaconda3/lib/python3.10/site-packages/evolocity/tools/velocity_graph.py:89, in predict_sequence_prob(seq_of_interest, vocabulary, model, verbose)
     87 if 'esm' in model.name_:
     88     from .fb_semantics import predict_sequence_prob_fb
---> 89     return predict_sequence_prob_fb(
     90         seq_of_interest, model.alphabet_, model.model_,
     91         model.repr_layers_, verbose=verbose,
     92     )
     93 elif model.name_ == 'tape':
     94     from .tape_semantics import predict_sequence_prob_tape

File ~/anaconda3/lib/python3.10/site-packages/evolocity/tools/fb_semantics.py:27, in predict_sequence_prob_fb(seq, alphabet, model, repr_layers, batch_size, verbose)
     21 data_loader = torch.utils.data.DataLoader(
     22     dataset, collate_fn=alphabet.get_batch_converter(),
     23     batch_sampler=batches
     24 )
     26 with torch.no_grad():
---> 27     for batch_idx, (labels, strs, toks) in enumerate(data_loader):
     28         if torch.cuda.is_available():
     29             toks = toks.to(device="cuda", non_blocking=True)

File ~/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py:628, in _BaseDataLoaderIter.__next__(self)
    625 if self._sampler_iter is None:
    626     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    627     self._reset()  # type: ignore[call-arg]
--> 628 data = self._next_data()
    629 self._num_yielded += 1
    630 if self._dataset_kind == _DatasetKind.Iterable and \
    631         self._IterableDataset_len_called is not None and \
    632         self._num_yielded > self._IterableDataset_len_called:

File ~/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py:671, in _SingleProcessDataLoaderIter._next_data(self)
    669 def _next_data(self):
    670     index = self._next_index()  # may raise StopIteration
--> 671     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    672     if self._pin_memory:
    673         data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

File ~/anaconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py:61, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     59 else:
     60     data = self.dataset[possibly_batched_index]
---> 61 return self.collate_fn(data)

File ~/anaconda3/lib/python3.10/site-packages/esm/data.py:266, in BatchConverter.__call__(self, raw_batch)
    264 batch_size = len(raw_batch)
    265 batch_labels, seq_str_list = zip(*raw_batch)
--> 266 seq_encoded_list = [self.alphabet.encode(seq_str) for seq_str in seq_str_list]
    267 if self.truncation_seq_length:
    268     seq_encoded_list = [seq_str[:self.truncation_seq_length] for seq_str in seq_encoded_list]

File ~/anaconda3/lib/python3.10/site-packages/esm/data.py:266, in <listcomp>(.0)
    264 batch_size = len(raw_batch)
    265 batch_labels, seq_str_list = zip(*raw_batch)
--> 266 seq_encoded_list = [self.alphabet.encode(seq_str) for seq_str in seq_str_list]
    267 if self.truncation_seq_length:
    268     seq_encoded_list = [seq_str[:self.truncation_seq_length] for seq_str in seq_encoded_list]

File ~/anaconda3/lib/python3.10/site-packages/esm/data.py:250, in Alphabet.encode(self, text)
    249 def encode(self, text):
--> 250     return [self.tok_to_idx[tok] for tok in self.tokenize(text)]

File ~/anaconda3/lib/python3.10/site-packages/esm/data.py:250, in <listcomp>(.0)
    249 def encode(self, text):
--> 250     return [self.tok_to_idx[tok] for tok in self.tokenize(text)]

KeyError: 'J'

**Comment by seyonechithrananda** [comment]
This problem was solved by using an older version of the ESM package, `fair-esm==0.31.1`, for anyone wondering!

**Comment by ronboger** [comment]
for clarity, it's actually `fair-esm==0.3.1`

**Comment by seyonechithrananda** [comment]
good catch, sorry about the typo!
