### ISSUE TITLE
Issues with long proteins (>1024 residues) with ESM_1b?

### ISSUE THREAD

**Issue by salvatoreloguercio** [brianhie/evolocity#2]
Hello, wondering if evolocity works with long proteins (>1024 residues) when embedding with ESM_1b - since the ESM repo reports issues with these proteins:
https://github.com/facebookresearch/esm/issues/49

Although I see that in the preprint that evolocity was used with e.g. Spike which is above 1024 residues.. So, not an issue?

**Comment by brianhie** [comment]
Hi @salvatoreloguercio, yes the 1024 residue limit of ESM-1b is unfortunate. The current workaround is to just divide the protein into 1022 residue windows (e.g., https://github.com/brianhie/evolocity/blob/2b162ff61d4239ba5af06a601e5bb62f501d4a0f/bin/fb_semantics.py#L12, 1022 + before/after sequence tokens), run these through the model separately, then concatenate the output, but this is definitely a heuristic.

Encouragingly, though, this seems to give reasonable results in the (zero-shot) deep mutational scan benchmark that contains long proteins (>1022 residues). For example, I think BRCA1 is longer than 1022, but the zero-shot mutational effect performance is still higher than DeepSequence.
